server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/dianshang0906?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: a123456

mybatis:
  mapperLocation: classpath:mapper/*.xml
  type-aliases-package: com.shenzhen.springcloud.entities    #所有entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true